inputs_def:
  - handle: video-path
    description: Input
    json_schema:
      anyOf:
        - type: string
          ui:widget: file
        - type: string
      ui:options:
        labels:
          - local-path
          - video-url
  - handle: source-language
    json_schema:
      enum:
        - ja
        - zh
        - en
      ui:options:
        labels:
          - ja
          - zh
          - en
    value: ""
  - handle: merge-subtitles-to-video
    json_schema:
      type: boolean
    value: false
  - handle: llm
    json_schema:
      anyOf:
        - type: "null"
        - type: object
          properties:
            api-key:
              contentMediaType: oomol/secret
              type: string
            model:
              type: string
            base-url:
              type: string
      ui:options:
        labels:
          - built-in-llm
          - custom-llm
    value:
      model: gemini-pro
    nullable: true
outputs_def:
  - handle: subtitle-path
    description: Output
    json_schema:
      type: string
      minLength: 1
      ui:widget: file
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: generate-subtitle
icon: ":fa6-solid:language:"
